version: '3.8'
services:
  turn:
    image: coturn/coturn:latest
    restart: always
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
    environment:
      - TURN_SECRET=${TURN_SECRET}